[build]
  publish = "public"
  command = "bun run build"

[build.environment]
  NODE_VERSION = "20"
  PYTHON_VERSION = "3.8"

# Use Ubuntu 20.04 Focal Fossa build image
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[[redirects]]
  from = "/rss.xml"
  to = "/rss.xml"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200