[build]
  publish = "public"
  command = """
    # Install Bun
    curl -fsSL https://bun.sh/install | bash
    export PATH="$HOME/.bun/bin:$PATH"
    
    # Install dependencies and build
    bun install
    bun run clean
    gatsby build
  """

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200